version: '3.8'
services:
  msc_database:
    image: postgres:15.3-alpine3.18
    container_name: 'msc_database'
    environment:
      - POSTGRES_USER=msc
      - POSTGRES_PASSWORD=msc
      - POSTGRES_DB=msc
    ports:
      - '5432:5432'
    volumes:
      - msc_db_data:/var/lib/postgresql/data
volumes:
  msc_db_data:
    driver: local